name: angular_ast
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/angular_ast
description: Parser and utilities for AngularDart templates
version: 0.2.0

environment:
  sdk: '>=1.20.0 <2.0.0'

dependencies:
  charcode: '^1.1.0'
  collection: '^1.12.0'
  string_scanner: '^1.0.0'
  quiver: '^0.22.0'

dev_dependencies:
  browser: '^0.10.0'
  codemirror: '^0.4.0'
  dart_style: '^0.2.13'
  js: '^0.6.0'
  path: '^1.4.1'
  test: '^0.12.17'
